// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pwr_msg.proto

package pwr_msg;

public final class PwrMsg {
  private PwrMsg() {}
  private static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface clinet_to_serverOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pwr_msg.clinet_to_server)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
     */
    pwr_msg.PwrMsg.clinet_to_server.type_of_massage getType();

    /**
     * <code>optional string login_string = 2;</code>
     */
    java.lang.String getLoginString();
    /**
     * <code>optional string login_string = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginStringBytes();

    /**
     * <code>optional string password_string = 3;</code>
     */
    java.lang.String getPasswordString();
    /**
     * <code>optional string password_string = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordStringBytes();

    /**
     * <code>optional string msg = 4;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code pwr_msg.clinet_to_server}
   */
  public  static final class clinet_to_server extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pwr_msg.clinet_to_server)
      clinet_to_serverOrBuilder {
    // Use clinet_to_server.newBuilder() to construct.
    private clinet_to_server(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private clinet_to_server() {
      type_ = 0;
      loginString_ = "";
      passwordString_ = "";
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private clinet_to_server(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              loginString_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              passwordString_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pwr_msg.PwrMsg.internal_static_pwr_msg_clinet_to_server_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pwr_msg.PwrMsg.internal_static_pwr_msg_clinet_to_server_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pwr_msg.PwrMsg.clinet_to_server.class, pwr_msg.PwrMsg.clinet_to_server.Builder.class);
    }

    /**
     * Protobuf enum {@code pwr_msg.clinet_to_server.type_of_massage}
     */
    public enum type_of_massage
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>registration = 0;</code>
       */
      registration(0),
      /**
       * <code>login = 1;</code>
       */
      login(1),
      /**
       * <code>connect_to_second_client = 2;</code>
       */
      connect_to_second_client(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>registration = 0;</code>
       */
      public static final int registration_VALUE = 0;
      /**
       * <code>login = 1;</code>
       */
      public static final int login_VALUE = 1;
      /**
       * <code>connect_to_second_client = 2;</code>
       */
      public static final int connect_to_second_client_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static type_of_massage valueOf(int value) {
        return forNumber(value);
      }

      public static type_of_massage forNumber(int value) {
        switch (value) {
          case 0: return registration;
          case 1: return login;
          case 2: return connect_to_second_client;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<type_of_massage>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          type_of_massage> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<type_of_massage>() {
              public type_of_massage findValueByNumber(int number) {
                return type_of_massage.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pwr_msg.PwrMsg.clinet_to_server.getDescriptor().getEnumTypes().get(0);
      }

      private static final type_of_massage[] VALUES = values();

      public static type_of_massage valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private type_of_massage(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pwr_msg.clinet_to_server.type_of_massage)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
     */
    public pwr_msg.PwrMsg.clinet_to_server.type_of_massage getType() {
      pwr_msg.PwrMsg.clinet_to_server.type_of_massage result = pwr_msg.PwrMsg.clinet_to_server.type_of_massage.valueOf(type_);
      return result == null ? pwr_msg.PwrMsg.clinet_to_server.type_of_massage.UNRECOGNIZED : result;
    }

    public static final int LOGIN_STRING_FIELD_NUMBER = 2;
    private volatile java.lang.Object loginString_;
    /**
     * <code>optional string login_string = 2;</code>
     */
    public java.lang.String getLoginString() {
      java.lang.Object ref = loginString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginString_ = s;
        return s;
      }
    }
    /**
     * <code>optional string login_string = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginStringBytes() {
      java.lang.Object ref = loginString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_STRING_FIELD_NUMBER = 3;
    private volatile java.lang.Object passwordString_;
    /**
     * <code>optional string password_string = 3;</code>
     */
    public java.lang.String getPasswordString() {
      java.lang.Object ref = passwordString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passwordString_ = s;
        return s;
      }
    }
    /**
     * <code>optional string password_string = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordStringBytes() {
      java.lang.Object ref = passwordString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passwordString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 4;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 4;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string msg = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != pwr_msg.PwrMsg.clinet_to_server.type_of_massage.registration.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getLoginStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginString_);
      }
      if (!getPasswordStringBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, passwordString_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != pwr_msg.PwrMsg.clinet_to_server.type_of_massage.registration.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getLoginStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginString_);
      }
      if (!getPasswordStringBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, passwordString_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pwr_msg.PwrMsg.clinet_to_server)) {
        return super.equals(obj);
      }
      pwr_msg.PwrMsg.clinet_to_server other = (pwr_msg.PwrMsg.clinet_to_server) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getLoginString()
          .equals(other.getLoginString());
      result = result && getPasswordString()
          .equals(other.getPasswordString());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + LOGIN_STRING_FIELD_NUMBER;
      hash = (53 * hash) + getLoginString().hashCode();
      hash = (37 * hash) + PASSWORD_STRING_FIELD_NUMBER;
      hash = (53 * hash) + getPasswordString().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pwr_msg.PwrMsg.clinet_to_server parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pwr_msg.PwrMsg.clinet_to_server prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pwr_msg.clinet_to_server}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pwr_msg.clinet_to_server)
        pwr_msg.PwrMsg.clinet_to_serverOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pwr_msg.PwrMsg.internal_static_pwr_msg_clinet_to_server_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pwr_msg.PwrMsg.internal_static_pwr_msg_clinet_to_server_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pwr_msg.PwrMsg.clinet_to_server.class, pwr_msg.PwrMsg.clinet_to_server.Builder.class);
      }

      // Construct using pwr_msg.PwrMsg.clinet_to_server.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        loginString_ = "";

        passwordString_ = "";

        msg_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pwr_msg.PwrMsg.internal_static_pwr_msg_clinet_to_server_descriptor;
      }

      public pwr_msg.PwrMsg.clinet_to_server getDefaultInstanceForType() {
        return pwr_msg.PwrMsg.clinet_to_server.getDefaultInstance();
      }

      public pwr_msg.PwrMsg.clinet_to_server build() {
        pwr_msg.PwrMsg.clinet_to_server result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pwr_msg.PwrMsg.clinet_to_server buildPartial() {
        pwr_msg.PwrMsg.clinet_to_server result = new pwr_msg.PwrMsg.clinet_to_server(this);
        result.type_ = type_;
        result.loginString_ = loginString_;
        result.passwordString_ = passwordString_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pwr_msg.PwrMsg.clinet_to_server) {
          return mergeFrom((pwr_msg.PwrMsg.clinet_to_server)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pwr_msg.PwrMsg.clinet_to_server other) {
        if (other == pwr_msg.PwrMsg.clinet_to_server.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getLoginString().isEmpty()) {
          loginString_ = other.loginString_;
          onChanged();
        }
        if (!other.getPasswordString().isEmpty()) {
          passwordString_ = other.passwordString_;
          onChanged();
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pwr_msg.PwrMsg.clinet_to_server parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pwr_msg.PwrMsg.clinet_to_server) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
       */
      public pwr_msg.PwrMsg.clinet_to_server.type_of_massage getType() {
        pwr_msg.PwrMsg.clinet_to_server.type_of_massage result = pwr_msg.PwrMsg.clinet_to_server.type_of_massage.valueOf(type_);
        return result == null ? pwr_msg.PwrMsg.clinet_to_server.type_of_massage.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
       */
      public Builder setType(pwr_msg.PwrMsg.clinet_to_server.type_of_massage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .pwr_msg.clinet_to_server.type_of_massage type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object loginString_ = "";
      /**
       * <code>optional string login_string = 2;</code>
       */
      public java.lang.String getLoginString() {
        java.lang.Object ref = loginString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string login_string = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginStringBytes() {
        java.lang.Object ref = loginString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string login_string = 2;</code>
       */
      public Builder setLoginString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string login_string = 2;</code>
       */
      public Builder clearLoginString() {
        
        loginString_ = getDefaultInstance().getLoginString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string login_string = 2;</code>
       */
      public Builder setLoginStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginString_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object passwordString_ = "";
      /**
       * <code>optional string password_string = 3;</code>
       */
      public java.lang.String getPasswordString() {
        java.lang.Object ref = passwordString_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          passwordString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string password_string = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordStringBytes() {
        java.lang.Object ref = passwordString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          passwordString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string password_string = 3;</code>
       */
      public Builder setPasswordString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        passwordString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string password_string = 3;</code>
       */
      public Builder clearPasswordString() {
        
        passwordString_ = getDefaultInstance().getPasswordString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string password_string = 3;</code>
       */
      public Builder setPasswordStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        passwordString_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 4;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 4;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 4;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 4;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pwr_msg.clinet_to_server)
    }

    // @@protoc_insertion_point(class_scope:pwr_msg.clinet_to_server)
    private static final pwr_msg.PwrMsg.clinet_to_server DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pwr_msg.PwrMsg.clinet_to_server();
    }

    public static pwr_msg.PwrMsg.clinet_to_server getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<clinet_to_server>
        PARSER = new com.google.protobuf.AbstractParser<clinet_to_server>() {
      public clinet_to_server parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new clinet_to_server(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<clinet_to_server> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<clinet_to_server> getParserForType() {
      return PARSER;
    }

    public pwr_msg.PwrMsg.clinet_to_server getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface server_to_clinetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pwr_msg.server_to_clinet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
     */
    pwr_msg.PwrMsg.server_to_clinet.type_of_massage getType();

    /**
     * <code>optional bool is_succesful = 2;</code>
     */
    boolean getIsSuccesful();

    /**
     * <code>optional string second_clinet_ip = 3;</code>
     */
    java.lang.String getSecondClinetIp();
    /**
     * <code>optional string second_clinet_ip = 3;</code>
     */
    com.google.protobuf.ByteString
        getSecondClinetIpBytes();
  }
  /**
   * Protobuf type {@code pwr_msg.server_to_clinet}
   */
  public  static final class server_to_clinet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pwr_msg.server_to_clinet)
      server_to_clinetOrBuilder {
    // Use server_to_clinet.newBuilder() to construct.
    private server_to_clinet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private server_to_clinet() {
      type_ = 0;
      isSuccesful_ = false;
      secondClinetIp_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private server_to_clinet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 16: {

              isSuccesful_ = input.readBool();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              secondClinetIp_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pwr_msg.PwrMsg.internal_static_pwr_msg_server_to_clinet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pwr_msg.PwrMsg.internal_static_pwr_msg_server_to_clinet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pwr_msg.PwrMsg.server_to_clinet.class, pwr_msg.PwrMsg.server_to_clinet.Builder.class);
    }

    /**
     * Protobuf enum {@code pwr_msg.server_to_clinet.type_of_massage}
     */
    public enum type_of_massage
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>registration_ack = 0;</code>
       */
      registration_ack(0),
      /**
       * <code>login_ack = 1;</code>
       */
      login_ack(1),
      /**
       * <code>connect_to_second_client_ack = 2;</code>
       */
      connect_to_second_client_ack(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>registration_ack = 0;</code>
       */
      public static final int registration_ack_VALUE = 0;
      /**
       * <code>login_ack = 1;</code>
       */
      public static final int login_ack_VALUE = 1;
      /**
       * <code>connect_to_second_client_ack = 2;</code>
       */
      public static final int connect_to_second_client_ack_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static type_of_massage valueOf(int value) {
        return forNumber(value);
      }

      public static type_of_massage forNumber(int value) {
        switch (value) {
          case 0: return registration_ack;
          case 1: return login_ack;
          case 2: return connect_to_second_client_ack;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<type_of_massage>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          type_of_massage> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<type_of_massage>() {
              public type_of_massage findValueByNumber(int number) {
                return type_of_massage.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pwr_msg.PwrMsg.server_to_clinet.getDescriptor().getEnumTypes().get(0);
      }

      private static final type_of_massage[] VALUES = values();

      public static type_of_massage valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private type_of_massage(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pwr_msg.server_to_clinet.type_of_massage)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
     */
    public pwr_msg.PwrMsg.server_to_clinet.type_of_massage getType() {
      pwr_msg.PwrMsg.server_to_clinet.type_of_massage result = pwr_msg.PwrMsg.server_to_clinet.type_of_massage.valueOf(type_);
      return result == null ? pwr_msg.PwrMsg.server_to_clinet.type_of_massage.UNRECOGNIZED : result;
    }

    public static final int IS_SUCCESFUL_FIELD_NUMBER = 2;
    private boolean isSuccesful_;
    /**
     * <code>optional bool is_succesful = 2;</code>
     */
    public boolean getIsSuccesful() {
      return isSuccesful_;
    }

    public static final int SECOND_CLINET_IP_FIELD_NUMBER = 3;
    private volatile java.lang.Object secondClinetIp_;
    /**
     * <code>optional string second_clinet_ip = 3;</code>
     */
    public java.lang.String getSecondClinetIp() {
      java.lang.Object ref = secondClinetIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secondClinetIp_ = s;
        return s;
      }
    }
    /**
     * <code>optional string second_clinet_ip = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSecondClinetIpBytes() {
      java.lang.Object ref = secondClinetIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secondClinetIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != pwr_msg.PwrMsg.server_to_clinet.type_of_massage.registration_ack.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (isSuccesful_ != false) {
        output.writeBool(2, isSuccesful_);
      }
      if (!getSecondClinetIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, secondClinetIp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != pwr_msg.PwrMsg.server_to_clinet.type_of_massage.registration_ack.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (isSuccesful_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isSuccesful_);
      }
      if (!getSecondClinetIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, secondClinetIp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pwr_msg.PwrMsg.server_to_clinet)) {
        return super.equals(obj);
      }
      pwr_msg.PwrMsg.server_to_clinet other = (pwr_msg.PwrMsg.server_to_clinet) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (getIsSuccesful()
          == other.getIsSuccesful());
      result = result && getSecondClinetIp()
          .equals(other.getSecondClinetIp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + IS_SUCCESFUL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSuccesful());
      hash = (37 * hash) + SECOND_CLINET_IP_FIELD_NUMBER;
      hash = (53 * hash) + getSecondClinetIp().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pwr_msg.PwrMsg.server_to_clinet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pwr_msg.PwrMsg.server_to_clinet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pwr_msg.server_to_clinet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pwr_msg.server_to_clinet)
        pwr_msg.PwrMsg.server_to_clinetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pwr_msg.PwrMsg.internal_static_pwr_msg_server_to_clinet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pwr_msg.PwrMsg.internal_static_pwr_msg_server_to_clinet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pwr_msg.PwrMsg.server_to_clinet.class, pwr_msg.PwrMsg.server_to_clinet.Builder.class);
      }

      // Construct using pwr_msg.PwrMsg.server_to_clinet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        isSuccesful_ = false;

        secondClinetIp_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pwr_msg.PwrMsg.internal_static_pwr_msg_server_to_clinet_descriptor;
      }

      public pwr_msg.PwrMsg.server_to_clinet getDefaultInstanceForType() {
        return pwr_msg.PwrMsg.server_to_clinet.getDefaultInstance();
      }

      public pwr_msg.PwrMsg.server_to_clinet build() {
        pwr_msg.PwrMsg.server_to_clinet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pwr_msg.PwrMsg.server_to_clinet buildPartial() {
        pwr_msg.PwrMsg.server_to_clinet result = new pwr_msg.PwrMsg.server_to_clinet(this);
        result.type_ = type_;
        result.isSuccesful_ = isSuccesful_;
        result.secondClinetIp_ = secondClinetIp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pwr_msg.PwrMsg.server_to_clinet) {
          return mergeFrom((pwr_msg.PwrMsg.server_to_clinet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pwr_msg.PwrMsg.server_to_clinet other) {
        if (other == pwr_msg.PwrMsg.server_to_clinet.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getIsSuccesful() != false) {
          setIsSuccesful(other.getIsSuccesful());
        }
        if (!other.getSecondClinetIp().isEmpty()) {
          secondClinetIp_ = other.secondClinetIp_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pwr_msg.PwrMsg.server_to_clinet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pwr_msg.PwrMsg.server_to_clinet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
       */
      public pwr_msg.PwrMsg.server_to_clinet.type_of_massage getType() {
        pwr_msg.PwrMsg.server_to_clinet.type_of_massage result = pwr_msg.PwrMsg.server_to_clinet.type_of_massage.valueOf(type_);
        return result == null ? pwr_msg.PwrMsg.server_to_clinet.type_of_massage.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
       */
      public Builder setType(pwr_msg.PwrMsg.server_to_clinet.type_of_massage value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .pwr_msg.server_to_clinet.type_of_massage type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private boolean isSuccesful_ ;
      /**
       * <code>optional bool is_succesful = 2;</code>
       */
      public boolean getIsSuccesful() {
        return isSuccesful_;
      }
      /**
       * <code>optional bool is_succesful = 2;</code>
       */
      public Builder setIsSuccesful(boolean value) {
        
        isSuccesful_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_succesful = 2;</code>
       */
      public Builder clearIsSuccesful() {
        
        isSuccesful_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object secondClinetIp_ = "";
      /**
       * <code>optional string second_clinet_ip = 3;</code>
       */
      public java.lang.String getSecondClinetIp() {
        java.lang.Object ref = secondClinetIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          secondClinetIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string second_clinet_ip = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSecondClinetIpBytes() {
        java.lang.Object ref = secondClinetIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secondClinetIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string second_clinet_ip = 3;</code>
       */
      public Builder setSecondClinetIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        secondClinetIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string second_clinet_ip = 3;</code>
       */
      public Builder clearSecondClinetIp() {
        
        secondClinetIp_ = getDefaultInstance().getSecondClinetIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string second_clinet_ip = 3;</code>
       */
      public Builder setSecondClinetIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        secondClinetIp_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:pwr_msg.server_to_clinet)
    }

    // @@protoc_insertion_point(class_scope:pwr_msg.server_to_clinet)
    private static final pwr_msg.PwrMsg.server_to_clinet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pwr_msg.PwrMsg.server_to_clinet();
    }

    public static pwr_msg.PwrMsg.server_to_clinet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<server_to_clinet>
        PARSER = new com.google.protobuf.AbstractParser<server_to_clinet>() {
      public server_to_clinet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new server_to_clinet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<server_to_clinet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<server_to_clinet> getParserForType() {
      return PARSER;
    }

    public pwr_msg.PwrMsg.server_to_clinet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pwr_msg_clinet_to_server_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pwr_msg_clinet_to_server_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pwr_msg_server_to_clinet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pwr_msg_server_to_clinet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpwr_msg.proto\022\007pwr_msg\"\325\001\n\020clinet_to_s" +
      "erver\0227\n\004type\030\001 \001(\0162).pwr_msg.clinet_to_" +
      "server.type_of_massage\022\024\n\014login_string\030\002" +
      " \001(\t\022\027\n\017password_string\030\003 \001(\t\022\013\n\003msg\030\004 \001" +
      "(\t\"L\n\017type_of_massage\022\020\n\014registration\020\000\022" +
      "\t\n\005login\020\001\022\034\n\030connect_to_second_client\020\002" +
      "\"\325\001\n\020server_to_clinet\0227\n\004type\030\001 \001(\0162).pw" +
      "r_msg.server_to_clinet.type_of_massage\022\024" +
      "\n\014is_succesful\030\002 \001(\010\022\030\n\020second_clinet_ip" +
      "\030\003 \001(\t\"X\n\017type_of_massage\022\024\n\020registratio",
      "n_ack\020\000\022\r\n\tlogin_ack\020\001\022 \n\034connect_to_sec" +
      "ond_client_ack\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pwr_msg_clinet_to_server_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pwr_msg_clinet_to_server_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pwr_msg_clinet_to_server_descriptor,
        new java.lang.String[] { "Type", "LoginString", "PasswordString", "Msg", });
    internal_static_pwr_msg_server_to_clinet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pwr_msg_server_to_clinet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pwr_msg_server_to_clinet_descriptor,
        new java.lang.String[] { "Type", "IsSuccesful", "SecondClinetIp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
